all: Task1 Task2

Task1: Task1.o
	gcc Task1.o -o Task1
Task2: Task2.o
	gcc Task2.o -o Task2
Task22: Task22.o
	gcc Task22.o -o Task22

Task1.o: Task1.c
	gcc -c Task1.c
Task2.o: Task2.c
	gcc -c Task2.c
Task22.: Task22.c
	gcc -c Task22.c
