all: T1 T2 T3 T4 T5

T1: T1.o
	gcc T1.o -o T1
T2: T1.o
	gcc T2.o -o T2
T3: T3.o
	gcc T3.o -o T3
T4: T4.o
	gcc T4.o -o T4
T5: T5.o
	gcc T5.o -o T5


T1.o: T1.c
	gcc -c T1.c
T2.o: T2.c
	gcc -c T2.c
T3.o: T3.c
	gcc -c T3.c
T4.o: T4.c
	gcc -c T4.c
T5.o: T5.c
	gcc -c T5.c


